### PR TITLE
Added support for custom database class and vfsName

### PR DESCRIPTION
**Pull request by gloubibou**
FMDatabasePool can now be subclassed to use a subclass of FMDatabase.
FMDatabasePool initializer now accepts a custom vfsName.

### CODE REVIEW

**Comment by ccgus** [comment]
Looks OK to me (though, tabs are being used instead of spaces- care to fix that?).

@robertmryan - any comments on this?

**Comment by robertmryan** [comment]
I guess it's OK, though it doesn't feel 100% right. It feels like there's some candidate for generics (though Objective-C only has "lightweight generics" at this point) or something like. And maybe there should be some assertion (not `NSAssert`; but production fatal error) to make sure that `databaseClass`, in fact, instantiates a `FMDatabase` subclass.

I might be inclined to keep `databaseClass` a private method (and go ahead and let gloubibou carry on with his subclassing approach for now), but let us stew over better, type-safe ways to do this in the long run.

**Comment by gloubibou** [comment]
I don’t actually use `databaseClass`. I added it to FMDatabasePool since it already existed on FMDatabaseQueue. I do use vfsName.

**Comment by gloubibou** [comment]
@ccgus I replaced the tabs with space

**Comment by ccgus** [comment]
Wait, so you added code that's never been executed? Boo! :)

It looks reasonable though, and it's private, so we'll keep it. Thanks for the patches!

**Pull request merged**
