### PR TITLE
add database open with VSF virtual file system

### PR DESCRIPTION
**Pull request by sechel**
Use FMDB in conjunction with, e.g., javerous/SMCryptoFile.

### CODE REVIEW

**Comment by ccgus** [comment]
I like this but there should be a could of changes first:

Rename it to:
openWithFlags:(int)flags vfs:(const char*)vfs

(Doesn't seem very cocoa-y to have "and" in there)

Add a similar interface to FMDatabaseQueue, so it's not left out.

And it doesn't seem very likely, but is there anyway to throw in a test or two for this?

**Comment by sechel** [comment]
Ok done. I added tests for opening a db with a custom virtual file system. FMDatabaseQueue is also included now. I also included a shared Scheme for the Tests target.
Greetings.

**Comment by ccgus** [comment]
Danke!

**Comment by mythodeia** [comment]
:+1:

**Pull request merged**
