### PR TITLE
Add FMDB/SQLCipher/FTS subspec

### PR DESCRIPTION
**Pull request by evands**
This allows SQLCipher+FTS.

### CODE REVIEW

**Comment by stephanheilner** [comment]
:+1: Works from my perspective, but it needs a bump in Podspec version as well (probably to 2.6?) @ccgus, would you be willing to create a new '2.6' tag after this is merged?

**Comment by evands** [comment]
Went ahead and bumped the version in the branch.

**Comment by binovsky** [comment]
Is it planed to merge this in near future?

**Comment by ccgus** [comment]
Well, it currently has conflicts. And I don't use cocoapods, so I'm not sure how best to test things out.

**Comment by evands** [comment]
Please see #503 :)

**Pull request closed without merging**
