### PR TITLE
Create variadic renditions of the FMDatabaseAdditions methods

### PR DESCRIPTION
**Pull request by robertmryan**
This is an extension that adds the variadic methods within the Objective-C FMDatabaseAdditions extension.

This addresses the problem identified in issue https://github.com/ccgus/fmdb/issues/336. 

Gus, I wasn't sure about the file name (it's getting a little unwieldy), but I wanted to conform to established patterns. Perhaps a shorter name would be better.

Also, it's worth noting that these methods return implicitly unwrapped optionals. This is a solid Swift pattern, but deviates a little from the Objective-C convention (for fundamental data types such as `int`, `double`, etc., at least). We could return non-optional values for those types if you wanted, but it feels like that's a step in the wrong direction (i.e. the Swift optional lets you differentiate between a `nil` value from `intForQuery` and a zero value).

### CODE REVIEW

**Comment by robertmryan** [comment]
By the way, I contemplated adding this to `FMDatabaseVariadic.swift`, but given that the additions is a separate extension, it felt appropriate to make this a separate extension, too.

**Comment by robertmryan** [comment]
BTW, @ccgus, even if you don't merge this pull request, you may want to take note of https://github.com/robertmryan/fmdb/commit/858216fb488b211efc1677287c29f07f12f4273f because that addresses a completely unrelated problem, whereby `applicationID` and `applicationIDString` appear to have been moved from `FMDatabase` to `FMDatabaseAdditions`, but the test cases were never updated correspondingly. That particular commit addresses that issue, moving a single test from `FMDatabaseTests` to `FMDatabaseAdditionsTests`.

**Comment by robertmryan** [comment]
By the way, the following tests demonstrate the behavior of the Swift variadic functions:

    class FMDatabaseAdditionsVariadicTests: XCTestCase {
        
        var db: FMDatabase!
        var databasePath: String!
        
        override func setUp() {
            super.setUp()
            
            let tempFolder = NSTemporaryDirectory()
            databasePath = tempFolder.stringByAppendingPathComponent("temp.sqlite")
            let fileManager = NSFileManager.defaultManager()
            
            if fileManager.fileExistsAtPath(databasePath) {
                var error: NSError?
                if (!fileManager.removeItemAtPath(databasePath, error: &error)) {
                    XCTFail("Unable to remove old database: \(error?.localizedDescription)")
                }
            }
            
            db = FMDatabase(path: databasePath)
            XCTAssertNotNil(db, "Unable to instantiate FMDatabase")
            
            var success = db.open()
            XCTAssert(success, "Unable to open database")
            
            success = db.executeUpdate("create table test (x integer, y text)")
            XCTAssert(success, "Unable to create table")
            
            success = db.executeUpdate("insert into test (x, y) values (?, ?)", 1, "foo")
            XCTAssert(success, "Unable to insert foo")
            
            success = db.executeUpdate("insert into test (y) values (?)",  "bar")
            XCTAssert(success, "Unable to insert bar")

            success = db.executeUpdate("insert into test (x) values (?)",  3)
            XCTAssert(success, "Unable to insert bar")
        }
        
        override func tearDown() {
            super.tearDown()
            
            let success = db.close()
            XCTAssert(success, "Unable to open database")
            
            var error: NSError?
            if (!NSFileManager.defaultManager().removeItemAtPath(databasePath, error: &error)) {
                XCTFail("Unable to delete \(databasePath)")
            }
            
            db = nil
            databasePath = nil
        }
        
        func testLongForQueryFoundNumeric() {
            let foo = db.longForQuery("select x from test where y = ?", "foo") as Int
            XCTAssertEqual(foo, 1, "foo should have been 1, but was \(foo)")
        }

        func testLongForQueryFoundNull() {
            let bar = db.longForQuery("select x from test where y = ?", "bar")
            XCTAssertNil(bar, "bar should have been 0, but was \(bar)")
        }
        
        func testLongForQueryNotFound() {
            let baz = db.longForQuery("select x from test where y = ?", "baz")
            XCTAssert(baz == nil, "baz should have been nil, but was \(baz)")
        }
        
        func testLongForQueryFoundString() {
            // Note, we're deliberately returning `y`, which will be `"foo"` and using `longForQuery`.
            // SQLite transparently does the conversion for us.

            let nonNumeric = db.longForQuery("select y from test where y = ?", "foo") as Int
            XCTAssertEqual(nonNumeric, 0, "foo should have been 1, but was \(nonNumeric)")
        }
        
        func testStringForQueryFoundString() {
            let foo = db.stringForQuery("select y from test where x = ?", 1) as String
            XCTAssertEqual(foo, "foo", "should have retrieved \"foo\" but retrieved \(foo)")
        }
        
        func testStringForQueryFoundNull() {
            let noValue = db.stringForQuery("select y from test where x = ?", 3)
            XCTAssertNil(noValue, "should have retrieve nil but retrieved \(noValue)")
        }
        
        func testStringForQueryFoundNothing() {
            let noValue = db.stringForQuery("select y from test where x = ?", 999)
            XCTAssertNil(noValue, "should have retrieve nil but retrieved \(noValue)")
        }

        func testStringForQueryFoundNumeric() {
            // Note, we're deliberate returning `x`, which is numeric value of 1, as using `stringForQuery`.
            // SQLite transparently does the conversion for us.

            let string = db.stringForQuery("select x from test where y = ?", "foo") as String
            XCTAssertEqual(string, "1", "should have retrieve \"1\" but retrieved \(string)")
        }
    }

**Comment by ccgus** [comment]
Some weirdness happened with conflicts and such- but… it's all up there now.  Danke!

**Comment by robertmryan** [comment]
Yeah, I saw that but wasn't sure why it happened. I just forked it yesterday. Oh well. Glad you were able to incorporate it without too much effort. 

I'll do pull request on reference docs, too, given that I changed comments in code with the intent of having that percolate through to that reference documentation, too. Note, appledoc uses Apple's new documentation layout, so it will look quite different.

**Pull request closed without merging**
