### PR TITLE
Don't force custom tokenizer module name

### PR DESCRIPTION
**Pull request by stephanheilner**
Most of the time when using FTS, you'll only need to use a single tokenizer. This change simplifies using a single tokenizer.

@newyankeecodeshop, could you check this out as well?

### CODE REVIEW

**Comment by newyankeecodeshop** [comment]
Good idea, but I would make one change. I think the name of the module should always be "fmdb". I'm not sure why we'd want to allow people to register modules under different names. I agree that we could have a registerTokenizer method that takes no name and just uses the default. Thoughts?

**Comment by stephanheilner** [comment]
I'm creating a database that's shared by an app on iOS, Android and Windows Phone. Android and Windows won't have any concept of what fmdb is. That was why I though it would make sense to allow developers to chose the module name.

**Comment by newyankeecodeshop** [comment]
Ah good point. I forgot there are other platforms out there. :-)

**Comment by stephanheilner** [comment]
@ccgus, let me know if you need me to change anything.

**Comment by ccgus** [comment]
I'm just queuing up FMDB stuff at the moment, no worries :)

**Comment by boshang** [comment]
good idea

**Comment by ccgus** [comment]
This patch breaks the tests.  Can you make sure that's fixed and running properly, and send a pull request again?

**Comment by stephanheilner** [comment]
Tests fixed as well as I added a new test for my changes.

**Comment by stephanheilner** [comment]
@ccgus, do you mean I should submit a fresh pull request, or is adding the fixes to the existing one okay?

**Comment by ccgus** [comment]
The existing one is fine.  Why are you changing FMDB's version number though?  I'm going to change that guy back to 2.4.  The "extras" folder isn't part of FMDB's core, so it doesn't get version bumps.

**Comment by stephanheilner** [comment]
I had changed the version because of CocoaPods. Basically, you don't use the master branch with CocoaPods, you use tagged releases, so in order for anyone with CocoaPods to get access to changes, a new tag needs to be created, and then the .podspec file needs to show the latest tag version. Its a CocoaPod-ism.

**Comment by ccgus** [comment]
I've bumped it to 2.5 now.

**Pull request merged**
