### PR TITLE
Framework branch

### PR DESCRIPTION
**Pull request by robertmryan**
Gus, I put the various framework-related changes in its own branch (see https://github.com/robertmryan/fmdb/tree/framework). This addresses the issues we raised in issue #https://github.com/ccgus/fmdb/issues/309.

This includes some code changes as well as adding a discussion in the README about how to create/use framework.

Please use or disregard as you see fit. I just wanted to get you the framework changes in its own branch so that you could put a branch in the main repo (rather than referring people to my fork).

### CODE REVIEW

**Comment by humblehacker** [comment]
Thanks for this @robertmryan.  I've been pointing to a specific commit for this in my project for a while now.  Having a branch to point to is a big improvement.  Getting it into the mainline would be even better. @ccgus?

**Comment by ccgus** [comment]
The sqlite3 to void changes are because of swift?
( https://github.com/robertmryan/fmdb/commit/11f67015996dce1aa5ff02bbb3d8b85bf773f3b7#diff-bf9a39a532f05f4d9ade7f2f48b23812L733 )

**Comment by ccgus** [comment]
Awwww crap, this broke apps :(  I'm going to have to back this out.

**Comment by ccgus** [comment]
Or I should say, this breaks builds.

**Comment by robertmryan** [comment]
@ccgus Sorry, I wasn't suggesting that this be merged into the `master` branch, but rather that this be incorporated as a `framework` branch in your repo. Sadly, to make this framework-compatible, this includes non-backward compatible changes. My apologies for not being more explicit on this point.

**Comment by ccgus** [comment]
No worries.

**Comment by felipesabino** [comment]
@robertmryan @ccgus this indeed broke a lot of my builds :cry: 

Can you guys point me to a branch or, preferably, a tag so that I can be frozen in time at least during this transition period?

**Comment by ccgus** [comment]
Sure- uh, look at the tags!

Also- I reverted the commit, so head should be exactly as it was before.

**Comment by robertmryan** [comment]
He already rolled it back.

**Comment by robertmryan** [comment]
@ccgus  BTW, is this going to be incorporated with a branch within the main repo? I don't want to delete it until I know you've got it OK.

**Comment by ccgus** [comment]
All done- I added a swiftFramework branch.  Thanks for doing this.

I'm planning on shipping my next big update later this month, and then I can focus on some of my side projects, like FMDB3 :)

**Pull request merged**
