### PR TITLE
Fix FMResultSet security weakness

### PR DESCRIPTION
**Pull request by arttrick**
A security weakness was detected as a result of detection by Facebook's infer.
The branch in the code will be taken when the pointer n is non-nil, but the programmer might have actually wanted the branch to be taken when the integer pointed to by n is nonzero. should programmer explicitly compare n to nil or call an accessor to clarify her intention.

### CODE REVIEW

**Comment by ccgus** [comment]
The code in FMDB is valid. I don't see how the patch improves things.

**Comment by robertmryan** [comment]
@ccgus - While I agree that this is not needed, I'd actually suggest we go ahead and do it. It's not critical, but it makes the intent more explicit and, more importantly, it eliminates a silly static analyzer warning. It's worth doing just to get a clean bill of health from the static analyzer.

I actually already have this in my pending 2.7.1 release (subject to your feedback, @ccgus, on that `valueLong` question, in issue https://github.com/ccgus/fmdb/issues/586).

**Comment by ccgus** [comment]
The problem with making this change is, that checking for a nil pointer this way is done all over the place in fmdb. I don't have Facebook's infer to try it out, but I'm assuming this isn't the only spot it happens? @arttrick do you see this warning in other places?

**Comment by robertmryan** [comment]
The problem isn't a `nil` pointer. The problem is that it's a `NSNumber *` pointer, and the static analyzer thinks it's ambiguous whether you really meant `if (n != nil) ...` or `if ([n boolValue]) ...`.

screenshot 2017-06-02 16 21 01

By making it `if (n != nil) ...` the ambiguity is removed.

**Comment by robertmryan** [comment]
@ccgus - AFAIK, this is the only `if` statement where we test `NSNumber *` pointer like this. 

Once this ambiguous reference was fixed it, I received a clean bill of health from the static analyzer.

**Comment by ccgus** [comment]
OK, I guess I'm alright with this one off. Is this is a special build of Clang that's using it? I can't get the Xcode analyzer to make the warning

**Comment by robertmryan** [comment]
Yeah, I only stumbled across it when I built a new macOS project in Xcode 8.3.2, and incorporated the FMDB source manually. I suspected some subtle build setting difference, but when I scanned through the build settings of the existing FMDB project and the new project, and nothing jumped out at me. It's funny. 

It's a bit like `valueLong` warning, which I've definitely seen once, but was not able to reproduce. It's frustrating. But in this case the analyzer warning is at least reproducible. If you want me to drop a project out there for you to look at, let me know.

**Comment by robertmryan** [comment]
I've incorporated this fix into 2.7.1, subject to @ccgus approval.

**Comment by arttrick** [comment]
@ccgus This problem is not detected elsewhere.
This problem is not a problem right now. However, there is a problem that the programmer's intentions are not clearly revealed due to unclear comparisons.

**Comment by ccgus** [comment]
And it's committed. Thanks all!

**Pull request closed without merging**
