### PR TITLE
Update FMDB.podspec

### PR DESCRIPTION
**Pull request by jamesstout**
added osx.deployment_target  = '10.11'

### CODE REVIEW

**Comment by Kaspik** [comment]
@ccgus Based on https://github.com/ccgus/fmdb/pull/743 we think minimum deployment target of this project is 10.11. But this `required` value is not mentioned in `podspec`. This results to all clients implementing `post_install` hook (see https://github.com/CocoaPods/CocoaPods/pull/10070 and https://github.com/CocoaPods/CocoaPods/issues/9884).

Please take a look and merge in, thank you! :)

**Comment by ccgus** [comment]
Thanks! (I don't use CocoaPods, but this looks reasonable so I'm merging)

**Comment by Kaspik** [comment]
@ccgus Thanks!

On similar note, your `SPM` `Package.swift` is missing completely the same :)

```
platforms: [
        .macOS(.v10_11),
    ],
```
https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html

**Comment by jamesstout** [comment]
Many thanks.

**Pull request merged**
